### ISSUE TITLE
Schedule Model

### ISSUE THREAD

**Issue by allenyong926** [allenyong926/BusTicketingSystem#11]
Guys our schedule model face one problem is the calendar....it will error, the error msg it say missing 1 thing

**Comment by CheowChenWei** [comment]
ok i go try find what problem

**Comment by tmwong95** [comment]
chenwei and yang i think i know wht missing ...name call jcalendar when u need use the calendar u should import this thing to netbean

**Comment by allenyong926** [comment]
ok tm i try to solve it 1st

**Comment by sh9312** [comment]
umm, guys the data fields are not retrieve whatever is in the database

**Comment by allenyong926** [comment]
i solve the calendar alrdy  we should import this to netbeans thn can solve it

[jcalendar-1.4.zip](https://github.com/allenyong926/BusTicketingSystem/files/670746/jcalendar-1.4.zip)

**Comment by allenyong926** [comment]
erm senghong i think u should add this to u netbean 
[mysql-connector-java-5.1.37-bin.zip](https://github.com/allenyong926/BusTicketingSystem/files/670750/mysql-connector-java-5.1.37-bin.zip)

**Comment by sh9312** [comment]
ok i'll try your suggestion first

**Comment by sh9312** [comment]
ohhh, it finally works

**Comment by allenyong926** [comment]
ok senghong
